name: missing-team-label
on:
  issues:
    types: [opened, unlabeled]
jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-create-comment@v1
        if: "${{ contains( join(github.event.issue.labels.*.name, ', '), 'team:') != true }}"
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}, please add a team label to this issue!